config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :items, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:create]
  end

  resources :dashboard, only: [:index]
  resources :bookings, only: [:update] do
    resources :reviews, only: [:index, :create, :update]
  end
  get "/", to: "front_end_development#homepage-search"

  get "/items-development", to: "front_end_development#index"
  get "/show-development", to: "front_end_development#show"
  get "/dashboard-development", to: "front_end_development#dashboard"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @review = Review.new
    @item = Item.new
  end

  def show
  end

  def create
  end

  def dashboard
  end
end

app/views/dashboard/_booking.html.erb
<div class="booking-card-grid" id="booking-card_<%= booking.id %>">
  <%= link_to item_path(booking.item), class: 'booking-card-grid-link' do %>
  <% end %>

  <%= render 'components/booking_cards/booking-card-request-info-and-message-sections', booking: booking %>

  <div class="booking-card-footer-right">
    <div class="mark-item-container">
    <!-- BUTTONS -->
    <% case booking.status %>
    <% when "requested" %>
        <%= link_to "Item received", booking_path(booking, status: 'borrowing'), {class: 'btn btn-green btn-sm', id: "item-received_#{booking.id}", method: :patch, remote: true} %>
    <% when "borrowing" %>
      <div class="mark-item-container">
        <%= link_to "Item returned", booking_path(booking, status: 'borrowed'), {class: 'btn btn-green btn-sm', id: "item-returned_#{booking.id}", method: :patch, remote: true} %>
      </div>
    <% when "borrowed" %>
      <% unless booking.review.present? %>
        <button type="button" class="btn btn-green btn-sm" data-toggle="modal" data-target="<%="#lr_modal_#{booking.id}" %>">
          Leave a review
        </button>
      <% end %>
    <% end %>
    <!-- / BUTTONS -->
    </div>
  </div>
  <%= render 'components/booking_cards/booking-card-image-container', booking: booking %>
  <%= render 'components/booking_cards/booking-card-footer', booking: booking %>
  <!-- MODAL -->
  <%= render 'components/leave-review-modal', booking: booking %>
  <%= render 'components/read-message-modal', booking: booking %>
</div>

app/views/dashboard/_my-items.html.erb
<div id="my-items-cards">
  <div class="cards-area">
    <!-- Modal trigger -->
    <div class="item-card-grid add-item-pointer" type="button" data-target="#exampleModalCenter" data-toggle="modal">
      <div class="new-item-block">
        <i class="fas fa-plus-circle add-item-lrg"></i>
        <h6>Add an item</h6>
      </div>
    </div>

    <% current_user.items.order(created_at: :desc).each do |item| %>
    <%= link_to item_path(item) do %>
    <div class="item-card-grid">
      <div class="item-card-image-container">
        <!-- item photo -->
        <% unless item.photo_fake == nil %>
        <div class="item-card-image" style="background-image: url(<%= item.photo_fake %>)
        "></div>
        <% else %>
        <div class="item-card-image" style="background-image: url(<%= cl_image_path item.photo %>)
        "></div>
        <% end %>
      </div>
      <div class="item-card-name">
        <h5><%= item.name %></h5>
      </div>
      <div class="item-card-description">
        <p><%= item.description %></p>
      </div>
      <div class="item-card-footer">
        <div class="card-rating-box">
          <% if item.comb_rating.nil? %>
          <h6><i class="fas fa-star align-middle"></i> n/a</h6>
          <% else %>
          <h6><i class="fas fa-star align-middle"></i> <%= item.comb_rating.round(1) %></h6>
          <% end %>
        </div>
        <div class="card-credits-box">
          <h4>b</h4>
          <h6> <%= item.credits %></h6>
        </div>
      </div>
      <% link_to item_path(item) %>
    </div>
    <% end %>
    <% end %>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLongTitle">Add an item</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <%= simple_form_for [@item] do |f| %>
          <% if @item.errors.any? %>
          <div class="errors-container">
            <ul>
              <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>

          <%= f.input :name, required: true %>
          <%= f.input :description, required: true %>
          <%= f.input :address, required: true %>
          <%= f.input :credits, label: 'Credits (1€ = 100 credits)', required: true, input_html: { min: '5'} %>
          <%= f.input :photo, required: true %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "add item", class: "btn btn-green" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_tabs.html.erb
<div class="tabs">
  <a class="tab active" id="requested" href="#">
    <h3><%= current_user.bookings.where(status: :requested).count %>
    </h3>
    <p>Requested</p>
  </a>
  <a class="tab" id="borrowing" href="#">
    <h3><%= current_user.bookings.where(status: :borrowing).count %></h3>
    <p>Borrowing</p>
  </a>
  <a class="tab" id="borrowed" href="#">
    <h3><%= current_user.bookings.where(status: :borrowed).count %></h3>
    <p>Borrowed</p>
  </a>
  <a class="tab" id="my-items" href="#">
    <h3><%= current_user.items.count %></h3>
    <p>My Items</p>
  </a>
</div>

app/views/dashboard/_user-area.html.erb
<div class="user-area">
  <div class="user-image-container">
    <div class="dashboard-user-image" style="background-image: url('<%= image_path current_user.photo_fake %>')"></div>
  </div>
  <div class="user-info inline">
    <div class="dashboard-user-first-name">
      <h4><%= current_user.first_name %></h4>
    </div>
    <div class="dashboard-user-rating">
      <div class="dashboard-rating-block-container inline">
        <div class="dashboard-rating-block">
          <% if current_user.average_rating.nil? %>
          <strong>n/a</strong>
          <% else %>
          <strong><%= current_user.average_rating.round(1) %></strong>
          <% end %>
        </div>
      </div>
      <% if current_user.average_rating.nil? %>
      <p>No reviews yet!</p>
      <% else %>
      <p>Your rating</p>
      <% end %>
    </div>
  </div>
  <div class="user-credits">
    <!-- <p><p class="credits-icon">b&nbsp;</p> -->
    <div id=credits-b>
      <h4>b</h4>
      <br>
    </div>
    <h3><strong>
      <%=number_with_delimiter(current_user.credits, :delimiter => ',') %>
    </strong></h3>
    <!-- <p>Credits</p> -->
  </div>
  <div class="user-stats inline">
    <div class="user-items-lent">
      <strong><%= current_user.items.count %></strong>
      <p>Items lent</p>
    </div>
    <div class="user-items-borrowed">
      <strong><%= current_user.bookings.count %></strong>
      <p>Items borrowed</p>
    </div>
  </div>
  <div class="buy-more-credits inline">
    <button type="button" class="btn btn-credits btn-green btn-sm">Buy More Credits</button>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= render 'shared/navbar' %>

<div class="wrapper">
  <div class="container">
    <div class="dashboard-index-grid">
      <%= render 'user-area' %>
      <div class="list-area" id="dashboard-tabs">
      <%= render 'tabs' %>

<!-- REQUESTED -->
      <div id="requested-booking-cards">
        <% current_user.bookings.where(status: :requested).order(updated_at: :desc).each do |booking| %>
          <%= render 'booking', booking: booking %>
        <% end %>
      </div>

<!-- BORROWING -->
      <div id="borrowing-booking-cards">
        <% current_user.bookings.where(status: :borrowing).order(updated_at: :desc).each do |booking| %>
          <%= render 'booking', booking: booking %>
        <% end %>
      </div>

<!-- BORROWED -->
        <div id="borrowed-booking-cards">
          <% current_user.bookings.where(status: :borrowed).order(updated_at: :desc).each do |booking| %>
            <%= render 'booking', booking: booking %>
          <% end %>
        </div>

<!-- MY ITEMS -->
        <%= render 'my-items' %>

      </div>
    </div>
  </div>
</div>

<% content_for :title, "Borrowbox - My Dashboard" %>