config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :items, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:create]
  end

  resources :dashboard, only: [:index]
  resources :bookings, only: [:update] do
    resources :reviews, only: [:index, :create, :update]
  end
  get "/", to: "front_end_development#homepage-search"

  get "/items-development", to: "front_end_development#index"
  get "/show-development", to: "front_end_development#show"
  get "/dashboard-development", to: "front_end_development#dashboard"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_homepage_navbar.html.erb
<div class="homepage-navbar-wagon">
  <!-- Logo -->

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

      <!-- Avatar with dropdown menu -->
      <!-- Login link (when logged out) -->
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-wagon-item homepage-navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-wagon-item homepage-navbar-wagon-link" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_homepage_navbar_signedin.html.erb
<div class="homepage-navbar-wagon-signedin">
  <!-- Logo -->

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.photo_fake, class: "avatar dropdown-toggle navbar-avatar", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_index_path do %>
                <i class="fas fa-tachometer-alt"></i> Dashboard
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i> Settings
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
          </ul>
        </div>
      </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_map_window.html.erb
<%= link_to item_path(item) do %>
<div class="map-card-grid">
  <div class="item-card-image-container">
    <!-- avatar -->
    <% unless item.user.photo_fake == nil %>
    <div class="map-card-avatar avatar-image position-absolute z-index-ten" style="background-image:url(<%= item.user.photo_fake %>)"></div>
    <% else %>
    <div class="map-card-avatar position-absolute z-index-ten" style="background-image: url(<%= cl_image_path item.user.photo %>)"></div>
    <% end %>
    <!-- item photo -->
    <% unless item.photo_fake == nil %>
    <div class="item-card-image" style="background-image: url(<%= item.photo_fake %>)
    "></div>
    <% else %>
    <div class="item-card-image" style="background-image: url(<%= cl_image_path item.photo %>)
    "></div>
    <% end %>
  </div>
  <div class="item-card-lender">
    <p><%= item.user.first_name %>'s</p>
  </div>
  <div class="map-card-name">
    <h6><%= item.name %></h6>
  </div>
  <div class="item-card-footer">
    <div class="card-rating-box">
      <% if item.comb_rating.nil? %>
        <h6><i class="fas fa-star align-middle"></i>n/a</h6>
      <% else %>
        <h6><i class="fas fa-star align-middle"></i> <%= item.comb_rating.round(1) %></h6>
      <% end %>
    </div>
    <div class="card-credits-box">
      <h4>b</h4>
      <h6><%= item.credits %></h6>
    </div>
  </div>
  <% link_to item_path(item) %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <div class="navbar-wagon-left">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo_white.png", height: 50 %>
    <% end %>
  </div>
  <!-- Logo -->


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%#= link_to "Dashboard", dashboard_index_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.photo_fake, class: "avatar dropdown-toggle navbar-avatar", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_index_path do %>
                <i class="fas fa-tachometer-alt"></i> Dashboard
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i> Settings
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>