config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :items, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:create]
  end

  resources :dashboard, only: [:index]
  resources :bookings, only: [:update] do
    resources :reviews, only: [:index, :create, :update]
  end
  get "/", to: "front_end_development#homepage-search"

  get "/items-development", to: "front_end_development#index"
  get "/show-development", to: "front_end_development#show"
  get "/dashboard-development", to: "front_end_development#dashboard"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings

  validates :name, presence: true
  # validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :photo, PhotoUploader

  def item_rating_bar
    reviews.average(:item_rating).nil? ? 0 : reviews.average(:item_rating).round(1)
  end

  def item_rating
    reviews.average(:item_rating)
  end

  private

  def calculate_average(ratings_array)
    if both_ratings_nil?
      nil
    elsif any_rating_nil?
      average_with_nils(ratings_array)
    else
      average(ratings_array)
    end
  end

  def both_ratings_nil?
    user.rating.nil? && rating.nil?
  end

  def any_rating_nil?
    user.rating.nil? || rating.nil?
  end

  def average(ratings_array)
    ratings_array.inject(0) { |sum, x| sum + x.to_f } / ratings_array.size
  end

  def average_with_nils(ratings_array)
    clean_ratings = ratings_array.compact
    average(clean_ratings)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @items =
      if sql_query.blank?
        Item.all
      else
        Item.where(sql_query,
                   max_credits: params[:max_credits],
                   min_rating: params[:min_rating],
                   name: "%#{params[:name]}%")
      end
    if params[:max_distance].present?
      @items = @items.near(params[:coordinates], params[:max_distance])
    elsif params[:address].present?
      @items = @items.near(params[:address])
    end
    # Mapbox
    @items = @items.where.not(latitude: nil, longitude: nil)

    @items = @items.paginate(:page => params[:page], :per_page => 9)

    @markers = markers(@items)
  end

  def show
    @item = Item.find(params[:id])
    @booking = Booking.new
    # Mapbox
    @markers = markers([@item])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.photo.present?
      @item.save
      redirect_to item_path(@item)
    else
      redirect_to dashboard_index_path
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to dashboard_index_path
  end

  private

  def sql_query
    query = []
    query << ':max_credits > credits' if params[:max_credits].present?
    query << ':min_rating <= comb_rating' if params[:min_rating].present?
    query << 'name ILIKE :name' if params[:name].present?
    query.join(' AND ')
  end

  def markers(items)
    items.map do |item|
      {
        lng: item.longitude,
        lat: item.latitude,
        infoWindow: { content: render_to_string(partial: "/shared/map_window", locals: { item: item }) }
      }
    end
  end

  def item_params
    params.require(:item).permit(:name, :description, :address, :credits, :photo)
  end
end

app/views/items/_cards.html.erb
<div class="cards-area">
  <% @items.each do |item| %>
  <%= link_to item_path(item) do %>
  <div class="item-card-grid">
    <div class="item-card-image-container">
      <!-- avatar -->
      <% unless item.user.photo_fake == nil %>
      <div class="card-avatar avatar-image position-absolute z-index-ten" style="background-image:url(<%= item.user.photo_fake %>)"></div>
      <% else %>
      <div class="card-avatar position-absolute z-index-ten" style="background-image: url(<%= cl_image_path item.user.photo %>)"></div>
      <% end %>
      <!-- item photo -->
      <% unless item.photo_fake == nil %>
      <div class="item-card-image" style="background-image: url(<%= item.photo_fake %>)
      "></div>
      <% else %>
      <div class="item-card-image" style="background-image: url(<%= cl_image_path item.photo %>)
      "></div>
      <% end %>
    </div>
    <div class="item-card-lender">
      <p><%= item.user.first_name %>'s</p>
    </div>
    <div class="item-card-name">
      <h5><%= item.name %></h5>
    </div>
    <div class="item-card-distance">
      <% unless item.distance_from(params[:coordinates]).nan? %>
        <p><%= item.distance_from(params[:coordinates]).round(1) %>km away</p>
      <% end %>
    </div>
    <div class="item-card-description">
      <p><%= item.description %></p>
    </div>
    <div class="item-card-footer">
      <div class="card-rating-box">
        <% if item.comb_rating.nil? %>
          <h6><i class="fas fa-star align-middle"></i>n/a</h6>
        <% else %>
          <h6><i class="fas fa-star align-middle"></i><%= item.comb_rating.round(1) %></h6>
        <% end %>
      </div>
      <div class="card-credits-box">
        <h4>b</h4>
        <h6> <%= item.credits %></h6>
      </div>
    </div>
    <% link_to item_path(item) %>
  </div>
  <% end %>
  <% end %>
  <%= will_paginate @items %>
</div>

app/views/items/_items_map.html.erb
<div
  id="map"
  style="width: 100%;
  height: 100%;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/items/_photo_form.html.erb
<%= simple_form_for(article) do |f| %>
  <!-- [...] -->
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <!-- [...] -->
<% end %>

app/views/items/_search_form.html.erb
<div class="row">
  <%= form_tag items_path, method: :get do %>
  <div class="col-xs-12 form-group font-sm">
    <label for="item">Item</label>
    <%= text_field_tag :name, params[:name], class: "form-control", placeholder: "What are you looking for?" %>
  </div>
  <div class="col-xs-12 form-group font-sm margin-boost">
    <label for="location">Location</label>
    <%= text_field_tag :address, params[:address], class: "form-control", placeholder: "Where are you searching?" %>
  </div>
  <div class="col-xs-5 form-group font-sm margin-boost">
    <label for="start-date">Between</label>
    <%= date_field_tag :start_date, params[:start_date], class: "form-control bg-white", id: 'booking_start_date', :placeholder => 'Earliest' %>
    </div>
    <div class="col-xs-2 form-group font-sm">
    <svg viewBox="0 0 24 24" role="presentation" aria-hidden="true" focusable="false" style="margin-top: 38px"><path d="m0 12.5a.5.5 0 0 0 .5.5h21.79l-6.15 6.15a.5.5 0 1 0 .71.71l7-7v-.01a.5.5 0 0 0 .14-.35.5.5 0 0 0 -.14-.35v-.01l-7-7a .5.5 0 0 0 -.71.71l6.15 6.15h-21.79a.5.5 0 0 0 -.5.5z" fill-rule="evenodd"></path></svg>
    </div>

  <div class="col-xs-5 form-group font-sm margin-boost">
    <label for="end-date"> </label>
    <%= date_field_tag :end_date, params[:end_date], class: "form-control bg-white", id: 'booking_end_date', :placeholder => 'Latest' %>
  </div>
  <div class="col-xs-12 form-group font-sm margin-boost">
    <label for="max-credits">Max credits</label>
    <%= number_field_tag :max_credits, params[:max_credits], class: "form-control", placeholder: "Max Credits", autofocus: true %>
  </div>
  <div class="col-xs-12 form-group font-sm margin-boost">
    <label for="max-distance">Max distance</label>
    <%= number_field_tag :max_distance, params[:max_distance], class: "form-control", placeholder: "Kilometers" %>
  </div>
  <div class="col-xs-12 rating-box">
    <!-- <div class="rating-box"> -->
      <fieldset class="rating">
        <%= radio_button_tag :min_rating, "5", params[:min_rating] == "5" %>
        <%= label_tag 'min_rating_5', '', class: "full" %>
        <%= radio_button_tag :min_rating, "4", params[:min_rating] == "4" %>
        <%= label_tag 'min_rating_4', '', class: "full" %>
        <%= radio_button_tag :min_rating, "3", params[:min_rating] == "3" %>
        <%= label_tag 'min_rating_3', '', class: "full" %>
        <%= radio_button_tag :min_rating, "2", params[:min_rating] == "2" %>
        <%= label_tag 'min_rating_2', '', class: "full" %>
        <%= radio_button_tag :min_rating, "1", params[:min_rating] == "1" %>
        <%= label_tag 'min_rating_1', '', class: "full" %>
      </fieldset>
      <a href="#" id="clear-button">Clear</a>
    <!-- </div> -->
  </div>
  <%= hidden_field_tag :coordinates %>
  <div class="col-xs-12">
    <button type="submit" class="btn btn-filter btn-green btn-sm" style="width: 100%; margin: 0px;">Filter</button>
  </div>
  <% end %>
</div>

app/views/items/index.html.erb
<%= render 'shared/navbar' %>

<div class="wrapper">

  <div class="container">
    <div class="index-grid">
      <div class="filter-area">
        <div class="filter-form">
          <%= render 'items/search_form' %>
        </div>
      </div>
      <div class="map-area">
        <%= render '/items/items_map' %>
      </div>
      <%= render "/items/cards" %>
    </div>
  </div>
</div>

<%= javascript_pack_tag "map" %>

<% content_for :title, "Borrowbox - Search" %>

app/views/items/show.html.erb
<%= render 'shared/navbar' %>

<div class="wrapper">
  <div class="container">
    <div class="grid">
      <%= render 'items/show/picture-frame' %>
      <%= render 'items/show/item-info-and-description.html' %>
      <%= render 'items/show/item-rating' %>
      <div class="item-reviews">
        <% @item.reviews.joins(:booking).order('bookings.end_date DESC').each do |review| %>
          <%= render 'items/show/review', review: review %>
        <% end %>
      </div>
      <%= render '/items/show/show_map' %>
      <!-- calendar -->
      <div class="item-calendar">
        <% if @item.user != current_user %>
          <%= render '/items/show/booking_form' %>
        <% else %>
          <div class="delete-item">
            <%= link_to "Delete this item", item_path(@item), class: "btn btn-lightgray btn-delete", method: :delete %>
          </div>
          <!-- <button class="btn btn-green btn-delete">Delete item</button> -->
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag "map" %>

<% content_for :title, "#{@item.name}" %>